# -*- coding: utf-8 -*-
"""Untitled15.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MuBYbcpY9rht1F7mr4iTgB5H2c98fJuk
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile book.py
# 
# class Book:
#     def __init__(self, title, author, isbn, available=True, borrow_count=0):
#         self.title = title.strip()
#         self.author = author.strip()
#         self.isbn = str(isbn).strip()
#         self.available = available
#         self.borrow_count = borrow_count
# 
#     def borrow(self):
#         if self.available:
#             self.available = False
#             self.borrow_count += 1
#             return True
#         return False
# 
#     def return_book(self):
#         self.available = True
# 
#     def to_dict(self):
#         return {
#             "title": self.title,
#             "author": self.author,
#             "isbn": self.isbn,
#             "available": self.available,
#             "borrow_count": self.borrow_count
#         }
# 
#     @staticmethod
#     def from_dict(data):
#         return Book(
#             data.get("title", ""),
#             data.get("author", ""),
#             data.get("isbn", ""),
#             data.get("available", True),
#             data.get("borrow_count", 0)
#         )
# 
#     def __str__(self):
#         status = "Available" if self.available else "Borrowed"
#         return f"{self.title} by {self.author} (ISBN: {self.isbn}) - {status}"
#

# Commented out IPython magic to ensure Python compatibility.
# %%writefile member.py
# class Member:
#     def __init__(self, name, member_id, borrowed_books=None):
#         self.name = name.strip()
#         self.member_id = str(member_id).strip()
#         self.borrowed_books = borrowed_books[:] if borrowed_books else []
# 
#     def borrow_book(self, book):
#         if book.borrow():
#             self.borrowed_books.append(book.isbn)
#             print(f"{self.name} borrowed {book.title}")
#         else:
#             print("Book not available!")
# 
#     def return_book(self, book):
#         if book.isbn in self.borrowed_books:
#             book.return_book()
#             self.borrowed_books.remove(book.isbn)
#             print(f"{self.name} returned {book.title}")
#         else:
#             print(f"{self.name} has not borrowed {book.title}.")
# 
#     def list_books(self):
#         return list(self.borrowed_books)
# 
#     def to_dict(self):
#         return {
#             "name": self.name,
#             "member_id": self.member_id,
#             "borrowed_books": self.borrowed_books
#         }
# 
#     @staticmethod
#     def from_dict(data):
#         return Member(
#             data.get("name", ""),
#             data.get("member_id", ""),
#             data.get("borrowed_books", [])
#         )
#

# Commented out IPython magic to ensure Python compatibility.
# %%writefile library.py
# import json
# from book import Book
# from member import Member
# 
# class Library:
#     def __init__(self):
#         self.books = []
#         self.members = []
#         self.load_data()
# 
#     def add_book(self, book):
#         self.books.append(book)
#         self.save_data()
# 
#     def register_member(self, member):
#         self.members.append(member)
#         self.save_data()
# 
#     def find_book(self, isbn):
#         return next((b for b in self.books if b.isbn == isbn), None)
# 
#     def find_member(self, member_id):
#         return next((m for m in self.members if m.member_id == member_id), None)
# 
#     def lend_book(self, member_id, isbn):
#         member = self.find_member(member_id)
#         book = self.find_book(isbn)
#         if member and book:
#             member.borrow_book(book)
#             self.save_data()
#         else:
#             print("Invalid member ID or book ISBN!")
# 
#     def take_return(self, member_id, isbn):
#         member = self.find_member(member_id)
#         book = self.find_book(isbn)
#         if member and book:
#             member.return_book(book)
#             self.save_data()
#         else:
#             print("Invalid return request!")
# 
#     def save_data(self):
#         try:
#             with open("books.json", "w", encoding="utf-8") as f:
#                 json.dump([b.to_dict() for b in self.books], f, indent=2)
#             with open("members.json", "w", encoding="utf-8") as f:
#                 json.dump([m.to_dict() for m in self.members], f, indent=2)
#         except Exception as e:
#             print("Error saving data:", e)
# 
#     def load_data(self):
#         try:
#             with open("books.json", "r", encoding="utf-8") as f:
#                 self.books = [Book.from_dict(b) for b in json.load(f)]
#         except:
#             self.books = []
# 
#         try:
#             with open("members.json", "r", encoding="utf-8") as f:
#                 self.members = [Member.from_dict(m) for m in json.load(f)]
#         except:
#             self.members = []
# 
#     def list_available_books(self):
#         if not self.books:
#             print("No books in the library yet.")
#             return
#         print("\nAvailable Books:")
#         for b in self.books:
#             if b.available:
#                 print(f"- {b.title} by {b.author} (ISBN: {b.isbn})")
# 
#     def list_members(self):
#         if not self.members:
#             print("No members registered yet.")
#             return
#         print("\nRegistered Members:")
#         for m in self.members:
#             print(f"- {m.name} (ID: {m.member_id})")
# 
#     def library_report(self):
#         borrowed_books = sum(1 for b in self.books if not b.available)
#         most_borrowed = max(self.books, key=lambda b: b.borrow_count, default=None)
# 
#         print("\n--- Library Report ---")
#         print(f"Total Active Members : {len(self.members)}")
#         print(f"Total Books         : {len(self.books)}")
#         print(f"Total Books Borrowed: {borrowed_books}")
#         if most_borrowed:
#             print(f"Most Borrowed Book  : {most_borrowed.title} ({most_borrowed.borrow_count} times)")
#         print("----------------------")
#

# Commented out IPython magic to ensure Python compatibility.
# %%writefile main.py
# from library import Library
# from book import Book
# from member import Member
# 
# lib = Library()
# print("\nWelcome to Library Management System")
# 
# while True:
#     print("\n--------- MENU ---------")
#     print("1. Add Book")
#     print("2. Register Member")
#     print("3. Borrow Book")
#     print("4. Return Book")
#     print("5. View Library Report")
#     print("6. View Available Books")
#     print("7. View Members")
#     print("8. Exit")
#     choice = input("Enter choice: ")
# 
#     if choice == "1":
#         title = input("Enter book title: ")
#         author = input("Enter author name: ")
#         isbn = input("Enter ISBN: ")
#         lib.add_book(Book(title, author, isbn))
#         print("Book added successfully!")
# 
#     elif choice == "2":
#         name = input("Enter member name: ")
#         member_id = input("Enter member ID: ")
#         lib.register_member(Member(name, member_id))
#         print("Member registered!")
# 
#     elif choice == "3":
#         member_id = input("Enter member ID: ")
#         isbn = input("Enter book ISBN: ")
#         lib.lend_book(member_id, isbn)
# 
#     elif choice == "4":
#         member_id = input("Enter member ID: ")
#         isbn = input("Enter ISBN: ")
#         lib.take_return(member_id, isbn)
# 
#     elif choice == "5":
#         lib.library_report()
# 
#     elif choice == "6":
#         lib.list_available_books()
# 
#     elif choice == "7":
#         lib.list_members()
# 
#     elif choice == "8":
#         print("Exiting... Goodbye!")
#         break
# 
#     else:
#         print("Invalid choice! Try again.")
#

# Commented out IPython magic to ensure Python compatibility.
# %run main.py